huellas_sanas/apps/Cita/urls.py
from django.urls import path, include  # Importa path para definir rutas de URL e include para incluir otras configuraciones de URL
from . import views  # Importa las vistas definidas en el directorio actual (directorio donde se encuentra este archivo)
from .views import cambiar_estado_pago

urlpatterns = [
    # Rutas para las citas
    # Listar las citas agendadas de la bd
    path('listar_citas', views.listar_citas, name="listar_citas"),
    # Agregar una cita
    path('agendar_cita', views.agendar_cita, name="agendar_cita"),
    # Le avise al usuario de que debe estar logeado para agendar una cita
    path('agendar_cita_sin_login', views.agendar_cita_sin_login, name="agendar_cita_sin_login"),
    # Editar una cita
    path('editar_cita/<int:cita_id>', views.editar_cita, name="editar_cita"),
    # Borrar una cita
    path('borrar_cita/<int:cita_id>', views.borrar_cita, name="borrar_cita"),
    # Confirmar antes de borrar una cita
    path('confirmar-borrar-cita/<int:cita_id>/', views.confirmar_borrar_cita, name='confirmar_borrar_cita'),
    path('confirmar-cancelar-cita/<int:cita_id>/', views.confirmar_cancelar_cita, name='confirmar_cancelar_cita'),

    # Listar las mascotas de la bd
    path('listar_mascotas', views.listar_mascotas, name="listar_mascotas"),
    # Agregar un empleado
    path('agregar_mascota', views.agregar_mascota, name="agregar_mascota"),
    # Editar un empleado
    path('editar_mascota/<int:mascota_id>', views.editar_mascota, name="editar_mascota"),
    # Borrar un empleado
    path('borrar_mascota/<int:mascota_id>', views.borrar_mascota, name="borrar_mascota"),
    # Confirmar antes de borrar un empleado
    path('confirmar-borrar-mascota/<int:mascota_id>/', views.confirmar_borrar_mascota, name='confirmar_borrar_mascota'),
    path('verificar-cliente/', views.verificar_cliente, name='verificar_cliente'),
    path('cita/cambiar_estado_pago/<int:cita_id>/', cambiar_estado_pago, name='cambiar_estado_pago'),
]

huellas_sanas/huellas_sanas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from . import views
from django.contrib.auth import views as auth_views 
from apps.Usuario.forms import ResetPasswordForm, NewPasswordForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: render(request, 'home.html'), name='home'),
    path('usuario/', include('apps.Usuario.urls')),
    path('cita/', include('apps.Cita.urls')),
    path('cuidado/', include('apps.Cuidado.urls')),
    path('transaccion/', include('apps.Transaccion.urls')),
    path('enviar_consulta/', views.enviar_consulta, name='enviar_consulta'),
    path('consulta_exitosa/', views.consulta_exitosa, name='consulta_exitosa'),
    path('sobre_nosotros/', views.sobre_nosotros, name='sobre_nosotros'),
    path('preguntas_frecuentes/', views.preguntas_frecuentes, name='preguntas_frecuentes'),
    path('login/', auth_views.LoginView.as_view(template_name='Usuario/login.html'), name='login'),
 # Login and Logout
    path('login/', LoginView.as_view(redirect_authenticated_user=True,template_name='Usuario/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='Usuario/logout.html'), name='logout'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="Usuario/reset_password.html", form_class=ResetPasswordForm), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="Usuario/reset_password_done.html"), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="Usuario/reset_password_confirm.html", form_class=NewPasswordForm), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name="Usuario/reset_password_complete.html"), name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

huellas_sanas/apps/Cita/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from apps.Usuario.models import Cliente, Empleado  # Importa las clases Cliente y Empleado

# Create your models here.

# Clase para almacenar información sobre las mascotas de los clientes
class Mascota(models.Model):
    ESPECIES_CHOICES = (
        ('Perro', 'Perro'),
        ('Gato', 'Gato'),
    )
    ESTADO_MASCOTA_CHOICES = [
    ('Sin atender', 'Sin atender'),
    ('En guardería', 'En guardería'),
    ('Siendo atendida', 'Siendo atendida'),
    ('En cirugía', 'En cirugía'),
    ('En cuidado post atención', 'En cuidado post atención'),
    ('Dada de alta', 'Dada de alta'),
    ('Fallecida', 'Fallecida'),
    # Agrega más opciones según sea necesario
]

    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    especie = models.CharField(max_length=50, choices=ESPECIES_CHOICES)
    raza = models.CharField(max_length=50)  
    estado = models.CharField(max_length=50, choices=ESTADO_MASCOTA_CHOICES, default='Sin atender', blank=True)

    def __str__(self):
        return self.nombre
    
class Cita(models.Model):
    MOTIVO_CHOICES = (
        ('Consulta Médica General', 'Consulta Médica General'),
        ('Esterilización', 'Esterilización'),
        ('Guardería', 'Guardería'),
        ('Peluquería', 'Peluquería'),
        ('Vacunación', 'Vacunación'),
    )

    ESTADO_CHOICES = (
        ('Programada', 'Programada'),
        ('Cancelada', 'Cancelada'),
        ('Realizada', 'Realizada'),
    )

    fecha = models.DateField()
    hora = models.TimeField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)
    veterinario = models.ForeignKey(
        Empleado,
        on_delete=models.CASCADE,
        limit_choices_to={'rol': 'Veterinario'}  # Filtra por el rol 'Veterinario'
    )
    motivo = models.CharField(max_length=50, choices=MOTIVO_CHOICES)
    estado = models.CharField(max_length=50, choices=ESTADO_CHOICES, default='Programada')  # Establece el valor por defecto
    ha_pagado = models.BooleanField(default=False, verbose_name="¿Ha pagado?")
    
    def __str__(self):
        return f'Cita para el cliente {self.cliente.user.username} con {self.veterinario.user.username} el {self.fecha} a las {self.hora}'

huellas_sanas/apps/Cita/forms.py
from django import forms
from .models import Cita, Mascota, Cliente
from datetime import time
from datetime import datetime, time
from django.utils import timezone
from pytz import timezone as tz
from django.core.exceptions import ValidationError
import pytz

HORARIO_CHOICES = [(time(hour, minute).strftime('%H:%M'), time(hour, minute).strftime('%I:%M %p')) for hour in range(9, 22) for minute in [0, 30]]


class CitaForm(forms.ModelForm):
    hora = forms.ChoiceField(choices=HORARIO_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    cliente_username = forms.CharField(
        label='Cliente',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    class Meta:
        model = Cita
        fields = ['cliente_username', 'veterinario', 'mascota', 'fecha', 'hora', 'motivo']
        widgets = {
            'veterinario': forms.Select(attrs={'class': 'form-control'}),
            'mascota': forms.Select(attrs={'class': 'form-control'}),
            'fecha': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'motivo': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean_cliente_username(self):
        username = self.cleaned_data.get('cliente_username')
        if username:
            try:
                cliente = Cliente.objects.get(user__username=username)
                return cliente
            except Cliente.DoesNotExist:
                raise forms.ValidationError("Cliente no encontrado. Asegúrese de ingresar un nombre de usuario válido.")
        else:
            raise forms.ValidationError("Este campo es requerido.")

    def clean(self):
        cleaned_data = super().clean()
        # Aquí puedes agregar otras validaciones
        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        cliente_username = self.cleaned_data.get('cliente_username')
        if cliente_username:
            instance.cliente = Cliente.objects.get(user__username=cliente_username)
        
        if commit:
            instance.save()
            self.save_m2m()
        return instance

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        self.fields['mascota'].queryset = Mascota.objects.none()
        if user and hasattr(user, 'cliente'):
            self.fields['cliente_username'].initial = user.username
            self.fields['mascota'].queryset = Mascota.objects.filter(cliente=user.cliente)
            self.fields['cliente_username'].widget = forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'})

        if 'cliente_username' in self.data:
            try:
                cliente_id = Cliente.objects.get(user__username=self.data.get('cliente_username')).id
                self.fields['mascota'].queryset = Mascota.objects.filter(cliente_id=cliente_id).order_by('nombre')
            except (ValueError, TypeError, Cliente.DoesNotExist):
                pass  # Cliente inválido o no encontrado

    def clean(self):
        cleaned_data = super().clean()
        fecha = cleaned_data.get('fecha')
        hora_str = cleaned_data.get('hora')

        if fecha and hora_str:
            hora = datetime.strptime(hora_str, '%H:%M').time()
            fecha_hora_seleccionada = datetime.combine(fecha, hora)
            local_timezone = pytz.timezone('America/Santiago')
            fecha_hora_seleccionada = local_timezone.localize(fecha_hora_seleccionada)
            now = datetime.now(local_timezone)

            if fecha_hora_seleccionada < now:
                self.add_error('fecha', 'No puedes seleccionar una hora en una fecha anterior a hoy.')

            veterinario = cleaned_data.get('veterinario')
            citas_existente = Cita.objects.filter(veterinario=veterinario, fecha=fecha, hora=hora)
            if self.instance and self.instance.pk:
                citas_existente = citas_existente.exclude(pk=self.instance.pk)

            if citas_existente.exists():
                self.add_error('hora', 'Ya hay una cita agendada para este veterinario en la misma fecha y hora.')

        return cleaned_data

class EditarCitaForm(forms.ModelForm):
    hora = forms.ChoiceField(choices=HORARIO_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    
    class Meta:
        model = Cita
        fields = ['veterinario','fecha', 'hora', 'motivo', 'estado']
        widgets = {
            'veterinario': forms.Select(attrs={'class': 'form-control'}),
            'fecha': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'hora': forms.Select(choices=HORARIO_CHOICES, attrs={'class': 'form-control'}),
            'motivo': forms.Select(attrs={'class': 'form-control'}),
            'estado': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        fecha = cleaned_data.get('fecha')
        hora_str = cleaned_data.get('hora')  # Obtener la hora como cadena

        if fecha and hora_str:
            hora = datetime.strptime(hora_str, '%H:%M').time()  # Convertir la cadena en objeto datetime.time
            fecha_hora_seleccionada = datetime.combine(fecha, hora)
            
            # Convertir a la zona horaria local (por ejemplo, 'America/Bogota')
            local_timezone = tz('America/Santiago')
            fecha_hora_seleccionada = local_timezone.localize(fecha_hora_seleccionada)
            now = timezone.localtime(timezone.now())  # Obtener la hora actual en la zona horaria local

            if fecha_hora_seleccionada < now:
                raise forms.ValidationError('No puedes seleccionar una hora en una fecha anterior a hoy.')

        veterinario = cleaned_data.get('veterinario')
        fecha = cleaned_data.get('fecha')
        hora = cleaned_data.get('hora')

        if veterinario and fecha and hora:
            # Verificar si ya existe una cita para el mismo veterinario en la misma fecha y hora
            citas_existente = Cita.objects.filter(veterinario=veterinario, fecha=fecha, hora=hora)

            if self.instance:
                # Si estamos editando una cita existente, excluimos esta cita de la consulta
                citas_existente = citas_existente.exclude(pk=self.instance.pk)

            if citas_existente.exists():
                # Si hay una cita existente, muestra un error de validación
                raise forms.ValidationError('Ya hay una cita agendada para este veterinario en la misma fecha y hora.')

        return cleaned_data

class MascotaForm(forms.ModelForm):
    cliente = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(MascotaForm, self).__init__(*args, **kwargs)
        # Restringir el campo 'estado' si el usuario es un cliente
        if self.user and hasattr(self.user, 'cliente'):
            self.fields['cliente'].widget.attrs['readonly'] = True
            self.fields['cliente'].initial = self.user.username
            # Establecer 'Sin atender' como único valor para el campo 'estado'
            self.fields['estado'].choices = [('Sin atender', 'Sin atender')]
        elif self.user and hasattr(self.user, 'empleado') and self.user.empleado.rol in ['Administrador', 'Recepcionista']:
            # Dejar todas las opciones si el usuario es un empleado con el rol adecuado
            self.fields['estado'].choices = Mascota.ESTADO_MASCOTA_CHOICES

    class Meta:
        model = Mascota
        fields = ['cliente', 'nombre', 'especie', 'raza', 'estado']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'especie': forms.Select(attrs={'class': 'form-control', 'id': 'id_especie'}),
            'raza': forms.Select(attrs={'class': 'form-control', 'id': 'id_raza'}),
            'estado': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        return nombre.capitalize()

    def clean_cliente(self):
        username_cliente = self.cleaned_data.get('cliente')
        try:
            cliente = Cliente.objects.get(user__username=username_cliente)
        except Cliente.DoesNotExist:
            raise ValidationError(f"Cliente con nombre de usuario '{username_cliente}' no existe.")
        return cliente

class EditarMascotaForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(EditarMascotaForm, self).__init__(*args, **kwargs)

        # Hacer los campos Nombre, Especie y Raza opcionales para veterinarios
        if self.user and hasattr(self.user, 'empleado') and self.user.empleado.rol == 'Veterinario':
            self.fields['nombre'].required = False
            self.fields['especie'].required = False
            self.fields['raza'].required = False

    class Meta:
        model = Mascota
        fields = ['nombre', 'especie', 'raza', 'estado']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'especie': forms.Select(attrs={'class': 'form-control', 'id': 'id_especie'}),
            'raza': forms.Select(attrs={'class': 'form-control', 'id': 'id_raza'}),  
            'estado': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        return nombre.capitalize()

huellas_sanas/templates/Cita/agregar_mascota.html
{% extends 'base.html' %}

{% block title %}Agregar Mascota{% endblock %}

{% block content %}
<div class="container">
  <h1>Agregar Mascota</h1>
  <form method="post">
    {% csrf_token %}
        
    <div class="form-group">
      <label for="id_cliente">Cliente:</label>
      {{ form.cliente }}
      <!-- Muestra errores específicos del campo cliente -->
      {% if form.cliente.errors %}
        <div class="alert alert-danger" role="alert">
          {% for error in form.cliente.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    
    <div class="form-group">
      <label for="id_nombre">Nombre:</label>
      {{ form.nombre }}
    </div>

    <div class="form-group">
      <label for="id_especie">Especie:</label>
      {{ form.especie }}
    </div>

    <div id="raza_field" style="display: none;" class="form-group">
      <label for="id_raza">Raza:</label>
      <select name="raza" id="id_raza" class="form-control"></select>
    </div>

    <div class="form-group">
      <label for="id_estado">Estado:</label>
      {{ form.estado }}
    </div>
    
    <!-- Agrega aquí los demás campos del formulario según tu formulario de Django -->

    <button type="submit" class="btn btn-primary">Agregar Mascota</button>

    {% if user.is_authenticated %}
      {% if user.empleado and user.empleado.rol == 'Veterinario' or user.empleado.rol == 'Administrador' or user.empleado.rol == 'Recepcionista' or user.cliente %}
        <a href="{% url 'listar_mascotas' %}" class="btn btn-secondary">Volver atrás</a>
      {% else %}
        <a href="{% url 'login' %}" class="btn btn-secondary">Volver atrás</a>
      {% endif %}
    {% else %}
      <a href="{% url 'login' %}" class="btn btn-secondary">Volver atrás</a>
    {% endif %}
  </form>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
  const especieSelect = document.getElementById('id_especie');
  const razaField = document.getElementById('raza_field');
  const razaSelect = document.getElementById('id_raza');

// Define un diccionario de razas para cada especie
const razasPorEspecie = {
  'Perro': [
    ['Akita Inu', 'Akita Inu'],
    ['Alaskan Malamute', 'Alaskan Malamute'],
    ['Barzoi', 'Barzoi'],
    ['Basset Azul de Gascuña', 'Basset Azul de Gascuña'],
    ['Basset Hound', 'Basset Hound'],
    ['Beagle', 'Beagle'],
    ['Beagle Harrier', 'Beagle Harrier'],
    ['Beauceron', 'Beauceron'],
    ['Bichón Maltés', 'Bichón Maltés'],
    ['Bobtail', 'Bobtail'],
    ['Border Collie', 'Border Collie'],
    ['Boxer', 'Boxer'],
    ['Boyero de Berna', 'Boyero de Berna'],
    ['Braco Alemán', 'Braco Alemán'],
    ['Braco Francés', 'Braco Francés'],
    ['Briard', 'Briard'],
    ['Bull terrier Inglés', 'Bull terrier Inglés'],
    ['Bulldog Francés', 'Bulldog Francés'],
    ['Bulldog Inglés', 'Bulldog Inglés'],
    ['Bullmastiff', 'Bullmastiff'],
    ['Cairn Terrier', 'Cairn Terrier'],
    ['Cane Corso', 'Cane Corso'],
    ['Caniche', 'Caniche'],
    ['Cavalier King Charles', 'Cavalier King Charles'],
    ['Chihuahua', 'Chihuahua'],
    ['Chow Chow', 'Chow Chow'],
    ['Cocker Spaniel Americano', 'Cocker Spaniel Americano'],
    ['Cocker Spaniel Inglés', 'Cocker Spaniel Inglés'],
    ['Collie Rough', 'Collie Rough'],
    ['Collie Smooth', 'Collie Smooth'],
    ['Dálmata', 'Dálmata'],
    ['Doberman', 'Doberman'],
    ['Dogo Argentino', 'Dogo Argentino'],
    ['Dogo de Burdeos', 'Dogo de Burdeos'],
    ['Epagneul Bretón', 'Epagneul Bretón'],
    ['Epagneul Francés', 'Epagneul Francés'],
    ['Epagneul Japonés', 'Epagneul Japonés'],
    ['Fox Terrier', 'Fox Terrier'],
    ['Galgo Español', 'Galgo Español'],
    ['Galgo Irlandés', 'Galgo Irlandés'],
    ['Golden Retriever', 'Golden Retriever'],
    ['Gordon Setter', 'Gordon Setter'],
    ['Gos d\'Atura', 'Gos d\'Atura'],
    ['Gran Danés', 'Gran Danés'],
    ['Husky Siberiano', 'Husky Siberiano'],
    ['Komondor', 'Komondor'],
    ['Labrador Retriever', 'Labrador Retriever'],
    ['Lebrel Afgano', 'Lebrel Afgano'],
    ['Lebrel Polaco', 'Lebrel Polaco'],
    ['Mastiff', 'Mastiff'],
    ['Mastín de los Pirineos', 'Mastín de los Pirineos'],
    ['Mastín Español', 'Mastín Español'],
    ['Mastín Napolitano', 'Mastín Napolitano'],
    ['Montaña de los Pirineos', 'Montaña de los Pirineos'],
    ['Norfolk Terrier', 'Norfolk Terrier'],
    ['Norwich Terrier', 'Norwich Terrier'],
    ['Otro', 'Otro'],
    ['Papillon', 'Papillon'],
    ['Pastor Alemán', 'Pastor Alemán'],
    ['Pastor Australiano', 'Pastor Australiano'],
    ['Pastor Belga', 'Pastor Belga'],
    ['Pastor Blanco Suizo', 'Pastor Blanco Suizo'],
    ['Pastor de los Pirineos', 'Pastor de los Pirineos'],
    ['Pekinés', 'Pekinés'],
    ['Pequeño Azul de Gascuña', 'Pequeño Azul de Gascuña'],
    ['Pequeño Basset Griffon', 'Pequeño Basset Griffon'],
    ['Pequeño Brabantino', 'Pequeño Brabantino'],
    ['Pequeño Perro León', 'Pequeño Perro León'],
    ['Pequeño Perro Ruso', 'Pequeño Perro Ruso'],
    ['Pequeño Sabueso Suizo', 'Pequeño Sabueso Suizo'],
    ['Perdiguero de Burgos', 'Perdiguero de Burgos'],
    ['Perdiguero Portugués', 'Perdiguero Portugués'],
    ['Perro de Agua Español', 'Perro de Agua Español'],
    ['Perro Lobo de Checoslovaquia', 'Perro Lobo de Checoslovaquia'],
    ['Pinscher miniatura', 'Pinscher miniatura'],
    ['Pit Bull', 'Pit Bull'],
    ['Podenco Canario', 'Podenco Canario'],
    ['Podenco Ibicenco', 'Podenco Ibicenco'],
    ['Pointer Inglés', 'Pointer Inglés'],
    ['Presa Canario', 'Presa Canario'],
    ['Pug', 'Pug'],
    ['Rafeiro do Alentejo', 'Rafeiro do Alentejo'],
    ['Rottweiler', 'Rottweiler'],
    ['Samoyedo', 'Samoyedo'],
    ['San Bernardo', 'San Bernardo'],
    ['Schnauzer gigante', 'Schnauzer gigante'],
    ['Schnauzer mediano', 'Schnauzer mediano'],
    ['Schnauzer miniatura', 'Schnauzer miniatura'],
    ['Scottish Terrier', 'Scottish Terrier'],
    ['Setter Inglés', 'Setter Inglés'],
    ['Setter Irlandés', 'Setter Irlandés'],
    ['Shar Pei', 'Shar Pei'],
    ['Shih Tzu', 'Shih Tzu'],
    ['Spitz', 'Spitz'],
    ['Springer Spaniel Galés', 'Springer Spaniel Galés'],
    ['Springer Spaniel Inglés', 'Springer Spaniel Inglés'],
    ['Teckel', 'Teckel'],
    ['Terranova', 'Terranova'],
    ['Weimaraner', 'Weimaraner'],
    ['Westies', 'Westies'],
    ['Whippet', 'Whippet'],
    ['Yorkshire Terrier', 'Yorkshire Terrier'],
  ],
  'Gato': [
    ['Abisinio', 'Abisinio'],
    ['Angora', 'Angora'],
    ['Azul Ruso', 'Azul Ruso'],
    ['Balinés', 'Balinés'],
    ['Bengal', 'Bengal'],
    ['Bobtail Japonés', 'Bobtail Japonés'],
    ['Bombay', 'Bombay'],
    ['Británico', 'Británico'],
    ['British Shorthair', 'British Shorthair'],
    ['Burmés', 'Burmés'],
    ['Burmilla', 'Burmilla'],
    ['Cartujo (Chartreux)', 'Cartujo (Chartreux)'],
    ['Cornish Rex', 'Cornish Rex'],
    ['Cymric (Man de pelo largo)', 'Cymric (Man de pelo largo)'],
    ['Del Bosque Noruego', 'Del Bosque Noruego'],
    ['Devon rex', 'Devon rex'],
    ['Exóticos', 'Exóticos'],
    ['Fold escocés', 'Fold escocés'],
    ['Foldex', 'Foldex'],
    ['Habana', 'Habana'],
    ['Himalayo', 'Himalayo'],
    ['Javanés', 'Javanés'],
    ['Korat', 'Korat'],
    ['Maine Coon', 'Maine Coon'],
    ['Manx', 'Manx'],
    ['Mau Egipcio', 'Mau Egipcio'],
    ['Munchkin', 'Munchkin'],
    ['Ocicat', 'Ocicat'],
    ['Oriental', 'Oriental'],
    ['Otro', 'Otro'],
    ['Pelicorto Americano', 'Pelicorto Americano'],
    ['Pelicorto Europeo', 'Pelicorto Europeo'],
    ['Persas', 'Persas'],
    ['Ragdoll\'s', 'Ragdoll\'s'],
    ['Rex selkirk', 'Rex selkirk'],
    ['Sagrados de Birmania', 'Sagrados de Birmania'],
    ['Siamés', 'Siamés'],
    ['Siberiano', 'Siberiano'],
    ['Singapur', 'Singapur'],
    ['Snowshoe', 'Snowshoe'],
    ['Somalí', 'Somalí'],
    ['Sphynx', 'Sphynx'],
    ['Tonquinés', 'Tonquinés'],
    ['Van turco', 'Van turco'],
  ]
};

  // Función para actualizar el campo de selección de razas
  function actualizarRazas() {
    const especieSeleccionada = especieSelect.value;
    razaSelect.innerHTML = ''; // Limpiar opciones anteriores

    if (especieSeleccionada in razasPorEspecie) {
      razaField.style.display = 'block'; // Mostrar el campo de selección de razas
      const razas = razasPorEspecie[especieSeleccionada];
      for (const raza of razas) {
        const option = document.createElement('option');
        option.value = raza[0];
        option.text = raza[1];
        razaSelect.appendChild(option);
      }
    } else {
      razaField.style.display = 'none'; // Ocultar el campo si no hay razas disponibles
    }
  }

  // Escuchar el evento de cambio en el campo de selección de especie
  especieSelect.addEventListener('change', actualizarRazas);

  // Llamar a la función de actualización inicialmente
  actualizarRazas();
});
</script>
{% endblock %}

huellas_sanas/templates/Cita/confirmar_borrar_mascota.html
{% extends 'base.html' %}

{% block title %}Confirmar Borrado de Mascota{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2>Confirmar Borrado</h2>
            <p>¿Estás seguro de que deseas eliminar la mascota "{{ mascota.nombre }}"?</p>
            <p><strong>Cliente:</strong> {{ mascota.cliente.user.username }}</p>
            <p><strong>Nombre de la mascota:</strong> {{ mascota.nombre }}</p>
            <p><strong>Especie:</strong> {{ mascota.get_especie_display }}</p>
            <p><strong>Raza:</strong> {{ mascota.raza }}</p>

            <form method="post">
                {% csrf_token %}
                <a href="{% url 'borrar_mascota' mascota.id %}" class="btn btn-danger">Confirmar Borrado</a>
                <a href="{% url 'listar_mascotas' %}" class="btn btn-secondary">Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}