huellas_sanas/apps/Cuidado/urls.py
from django.urls import path
from . import views
from .views import verificar_cliente_ficha, generar_ficha_pdf

urlpatterns = [
    # Rutas para fichas
    path('listar_fichas', views.listar_fichas, name="listar_fichas"),
    path('agregar_ficha', views.agregar_ficha, name="agregar_ficha"),
    path('editar_ficha/<int:ficha_id>', views.editar_ficha, name="editar_ficha"),
    path('borrar_ficha/<int:ficha_id>', views.borrar_ficha, name="borrar_ficha"),
    path('confirmar-borrar-ficha/<int:ficha_id>/', views.confirmar_borrar_ficha, name='confirmar_borrar_ficha'),
    path('verificar-cliente-ficha/', verificar_cliente_ficha, name='verificar_cliente_ficha'),
    path('fichas/generar_pdf/<int:id_ficha>/', generar_ficha_pdf, name='generar_ficha_pdf'),
]

huellas_sanas/huellas_sanas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from . import views
from django.contrib.auth import views as auth_views 
from apps.Usuario.forms import ResetPasswordForm, NewPasswordForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: render(request, 'home.html'), name='home'),
    path('usuario/', include('apps.Usuario.urls')),
    path('cita/', include('apps.Cita.urls')),
    path('cuidado/', include('apps.Cuidado.urls')),
    path('transaccion/', include('apps.Transaccion.urls')),
    path('enviar_consulta/', views.enviar_consulta, name='enviar_consulta'),
    path('consulta_exitosa/', views.consulta_exitosa, name='consulta_exitosa'),
    path('sobre_nosotros/', views.sobre_nosotros, name='sobre_nosotros'),
    path('preguntas_frecuentes/', views.preguntas_frecuentes, name='preguntas_frecuentes'),
    path('login/', auth_views.LoginView.as_view(template_name='Usuario/login.html'), name='login'),
 # Login and Logout
    path('login/', LoginView.as_view(redirect_authenticated_user=True,template_name='Usuario/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='Usuario/logout.html'), name='logout'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="Usuario/reset_password.html", form_class=ResetPasswordForm), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="Usuario/reset_password_done.html"), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="Usuario/reset_password_confirm.html", form_class=NewPasswordForm), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name="Usuario/reset_password_complete.html"), name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

huellas_sanas/apps/Cuidado/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from apps.Usuario.models import Cliente, Empleado  # Importa las clases Cliente y Empleado
from apps.Cita.models import Mascota # Importa la clase Mascota

# Create your models here.

# Clase para registrar fichas médicas y tratamientos para las mascotas
class Ficha(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)  # Relación con la mascota asociada a la ficha
    veterinario = models.ForeignKey(
        Empleado,
        on_delete=models.CASCADE,
        limit_choices_to={'rol': 'Veterinario'}  # Filtra por el rol 'Veterinario'
    )
    fecha = models.DateField()
    medicamento = models.CharField(max_length=100)
    dosis = models.CharField(max_length=50)
    instrucciones = models.TextField()

    def __str__(self):
        return f'Ficha para {self.mascota.nombre} por {self.veterinario.user.username} el {self.fecha}'
    

huellas_sanas/apps/Cuidado/forms.py
from django import forms
from apps.Cita.models import Mascota
from .models import Ficha
from apps.Usuario.models import Cliente

class FichaForm(forms.ModelForm):
    cliente_username = forms.CharField(
        label='Cliente',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True
    )

    class Meta:
        model = Ficha
        exclude = ['cliente']
        widgets = {
            'mascota': forms.Select(attrs={'class': 'form-control'}),
            'veterinario': forms.Select(attrs={'class': 'form-control'}),
            'fecha': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'medicamento': forms.TextInput(attrs={'class': 'form-control'}),
            'dosis': forms.TextInput(attrs={'class': 'form-control'}),
            'instrucciones': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

    def clean_cliente_username(self):
        username = self.cleaned_data.get('cliente_username')
        try:
            cliente = Cliente.objects.get(user__username=username)
            return cliente
        except Cliente.DoesNotExist:
            raise forms.ValidationError("Cliente no encontrado. Asegúrese de ingresar un nombre de usuario válido.")
        
    def save(self, commit=True):
        ficha = super().save(commit=False)
        username = self.cleaned_data.get('cliente_username')
        if username:
            cliente = Cliente.objects.get(user__username=username)
            ficha.cliente = cliente
        if commit:
            ficha.save()
            self.save_m2m()
        return ficha

    def __init__(self, *args, **kwargs):
        exclude_fields = kwargs.pop('exclude_fields', [])
        super(FichaForm, self).__init__(*args, **kwargs)
        self.fields['mascota'].queryset = Mascota.objects.none()

        # Excluir campos si se especifican
        for field in exclude_fields:
            if field in self.fields:
                del self.fields[field]

        if 'cliente_username' in self.data:
            try:
                cliente_id = Cliente.objects.get(user__username=self.data.get('cliente_username')).id
                self.fields['mascota'].queryset = Mascota.objects.filter(cliente_id=cliente_id).order_by('nombre')
            except (ValueError, TypeError, Cliente.DoesNotExist):
                pass  # Cliente inválido o no encontrado

huellas_sanas/apps/Cuidado/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Ficha
from .forms import FichaForm
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from apps.Cita.models import Mascota
from apps.Usuario.models import Cliente 
from reportlab.pdfgen import canvas
from django.http import HttpResponse
from .models import Ficha
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import io 

@login_required
def listar_fichas(request):
    # Vista para listar fichas con opciones de búsqueda y paginación

    # Obtener el usuario actualmente logeado
    user = request.user

    # Inicializar la variable de consulta para todas las fichas
    fichas = Ficha.objects.all()

    # Obtener el valor de búsqueda del parámetro 'mascota' en la URL
    mascota_query = request.GET.get('mascota')

    if user.is_authenticated:
        # Si el usuario está autenticado

        # Si el usuario es un Cliente, filtrar fichas por sus mascotas
        if hasattr(user, 'cliente'):
            fichas = fichas.filter(mascota__cliente=user.cliente)
        elif user.empleado and user.empleado.rol == 'Veterinario':
            # Si el usuario es un Empleado con el rol de Veterinario, no aplicar ningún filtro
            pass
        else:
            # Otros usuarios no permitidos, redireccionar o mostrar un mensaje de error según sea necesario
            # Puedes personalizar esto de acuerdo a tus requerimientos
            return HttpResponse("Acceso no autorizado")

        # Si se proporcionó un valor de búsqueda de mascota, filtrar fichas por mascota
        if mascota_query:
            fichas = fichas.filter(mascota__nombre__icontains=mascota_query)

        # Configurar la paginación
        paginator = Paginator(fichas, 5)  # Mostrar 5 fichas por página
        page = request.GET.get('page')  # Obtener el número de página de la solicitud GET

        try:
            fichas = paginator.page(page)
        except PageNotAnInteger:
            fichas = paginator.page(1)  # Si la página no es un número entero, mostrar la primera página
        except EmptyPage:
            fichas = paginator.page(paginator.num_pages)  # Si la página está fuera de rango, mostrar la última página

        # Agregar una variable de contexto para indicar si se ha realizado una búsqueda
        has_search_query_mascota = bool(mascota_query)
    else:
        # Si el usuario no está autenticado, puedes redirigirlo a la página de inicio de sesión o mostrar un mensaje de error
        # Puedes personalizar esto según tus necesidades
        return HttpResponse("Acceso no autorizado")

    return render(request, 'Cuidado/listar_fichas.html', {
        'fichas': fichas,
        'has_search_query_mascota': has_search_query_mascota,
    })

@login_required
def generar_ficha_pdf(request, id_ficha):
    ficha = Ficha.objects.get(id=id_ficha)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="ficha_medica_{id_ficha}.pdf"'

    buffer = io.BytesIO()
    
    # Creamos un documento PDF con el buffer como su "archivo"
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)

    # Creamos un arreglo de 'Flowables' para agregar al documento
    flowables = []

    # Obtenemos el estilo de ReportLab y creamos estilos para los párrafos
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', alignment=1))

    # Agregamos los datos de la ficha
    flowables.append(Paragraph(f"Empresa: Huellas Sanas S.A."))
    flowables.append(Paragraph(f"Cliente: {ficha.cliente.user.username}", styles['Normal']))
    flowables.append(Paragraph(f"Mascota: {ficha.mascota.nombre}", styles['Normal']))
    flowables.append(Paragraph(f"Veterinario: {ficha.veterinario.user.get_full_name()}", styles['Normal']))
    flowables.append(Paragraph(f"Fecha: {ficha.fecha.strftime('%d/%m/%Y')}", styles['Normal']))
    flowables.append(Paragraph(f"Medicamento: {ficha.medicamento}", styles['Normal']))
    flowables.append(Paragraph(f"Dosis: {ficha.dosis}", styles['Normal']))
    flowables.append(Spacer(1, 12))
    flowables.append(Paragraph(f"Instrucciones:", styles['Normal']))
    flowables.append(Paragraph(f"{ficha.instrucciones}", styles['Justify']))

    # Construimos el documento con los flowables
    doc.build(flowables)

    # Movemos el valor del buffer al response para que se descargue el archivo PDF
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response

@login_required
def agregar_ficha(request):
    if request.method == "POST":
        form = FichaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ficha agregada con éxito.')
            return redirect('listar_fichas')
    else:
        form = FichaForm()

    return render(request, "Cuidado/agregar_ficha.html", {'form': form})

def verificar_cliente_ficha(request):
    username = request.GET.get('username')
    try:
        cliente = Cliente.objects.get(user__username=username)
        mascotas = Mascota.objects.filter(cliente=cliente)
        mascotas_data = [{'id': mascota.id, 'nombre': mascota.nombre} for mascota in mascotas]
        return JsonResponse({'mascotas': mascotas_data, 'existe': True})
    except Cliente.DoesNotExist:
        return JsonResponse({'existe': False})
    
@login_required
def editar_ficha(request, ficha_id):
    instancia = Ficha.objects.get(id=ficha_id)

    if request.method == "POST":
        form = FichaForm(request.POST, instance=instancia, exclude_fields=['cliente_username', 'cliente', 'veterinario', 'mascota'])
        if form.is_valid():
            form.save()
            messages.success(request, 'Ficha editada con éxito.')
            return redirect('listar_fichas')
    else:
        fecha_actual = instancia.fecha.strftime('%Y-%m-%d')
        form = FichaForm(instance=instancia, initial={'fecha': fecha_actual}, exclude_fields=['cliente_username', 'cliente', 'veterinario', 'mascota'])

    return render(request, "Cuidado/editar_ficha.html", {'form': form})

@login_required
def confirmar_borrar_ficha(request, ficha_id):
    # Vista para confirmar la eliminación de una ficha

    ficha = Ficha.objects.get(id=ficha_id)
    return render(request, 'Cuidado/confirmar_borrar_ficha.html', {'ficha': ficha})

@login_required
def borrar_ficha(request, ficha_id):
    # Vista para borrar una ficha existente

    try:
        instancia = Ficha.objects.get(id=ficha_id)
        instancia.delete()
        messages.success(request, 'Ficha eliminada con éxito.')  # Agrega mensaje de éxito
    except Ficha.DoesNotExist:
        pass  # Manejar la situación en la que la ficha no existe

    return redirect('listar_fichas')  # Redirige a la lista de fichas después de borrar una

huellas_sanas/templates/Cuidado/agregar_ficha.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Agregar Ficha Médica{% endblock %}

{% block content %}
<div class="container">
    <h1>Agregar Ficha Médica</h1>
    <form method="post" id="formFicha">
        {% csrf_token %}
        
        <!-- Campo Cliente -->
        <div class="form-group">
          <label for="id_cliente_username">{{ form.cliente_username.label }}</label>
          {{ form.cliente_username|add_class:"form-control" }}
          {% if form.cliente_username.errors %}
          <div class="alert alert-danger">
              {{ form.cliente_username.errors.as_text }}
          </div>
          {% endif %}
          <button type="button" id="verificarCliente" class="btn btn-info mt-2">Verificar Cliente</button>
        </div>

        <!-- Resto de campos, excluyendo 'cliente' -->
        {% for field in form %}
          {% if field.name != 'cliente_username' %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field|add_class:"form-control" }}
                {% if field.errors %}
                <div class="alert alert-danger">
                    {{ field.errors.as_text }}
                </div>
                {% endif %}
            </div>
          {% endif %}
        {% endfor %}

        <button type="submit" class="btn btn-primary">Agregar Ficha</button>
        <a href="{% url 'listar_fichas' %}" class="btn btn-secondary">Volver atrás</a>
    </form>
</div>

<script>
document.getElementById('verificarCliente').addEventListener('click', function() {
    var username = document.getElementById('id_cliente_username').value;
    fetch('{% url "verificar_cliente_ficha" %}?username=' + username)
        .then(response => response.json())
        .then(data => {
            if (data.existe) {
                var selectMascotas = document.getElementById('id_mascota');
                selectMascotas.innerHTML = '';
                data.mascotas.forEach(function(mascota) {
                    var option = document.createElement('option');
                    option.value = mascota.id;
                    option.textContent = mascota.nombre;
                    selectMascotas.appendChild(option);
                });
            } else {
                alert('Cliente no encontrado.');
            }
        })
        .catch(error => {
            console.error('Error al verificar el cliente:', error);
            alert('Ocurrió un error al verificar el cliente.');
        });
});
</script>
{% endblock %}

huellas_sanas/templates/Cuidado/confirmar_borrar_ficha.html
{% extends 'base.html' %}

{% block title %}Confirmar Borrado de Ficha Médica{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2>Confirmar Borrado</h2>
            <p>¿Estás seguro de que deseas eliminar la ficha con ID {{ ficha.id }} de la base de datos?</p>
            <p><strong>Cliente:</strong> {{ ficha.cliente.user.username }}</p>
            <p><strong>Mascota:</strong> {{ ficha.mascota.nombre }}</p>
            <p><strong>Veterinario:</strong> {{ ficha.veterinario.user.username }}</p>
            <p><strong>Fecha:</strong> {{ ficha.fecha }}</p>
            <p><strong>Medicamento:</strong> {{ ficha.medicamento }}</p>
            <p><strong>Dosis:</strong> {{ ficha.dosis }}</p>
            <p><strong>Instrucciones:</strong> {{ ficha.instrucciones }}</p>

            <form method="post">
                {% csrf_token %}
                <a href="{% url 'borrar_ficha' ficha.id %}" class="btn btn-danger">Confirmar Borrado</a>
                <a href="{% url 'listar_fichas' %}" class="btn btn-secondary">Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

huellas_sanas/templates/Cuidado/editar_ficha.html
{% extends 'base.html' %}

{% block title %}Editar Ficha Médica{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Editar Ficha Médica</h2>
    <form method="post">
        {% csrf_token %}
        <!-- Renderiza cada campo individualmente, excluyendo 'cliente' -->
        {% for field in form %}
            {% if field.name != 'cliente' %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                        <div class="alert alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
            {% endif %}
        {% endfor %}

        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        <a href="{% url 'listar_fichas' %}" class="btn btn-secondary">Volver atrás</a>
    </form>
</div>
{% endblock %}

huellas_sanas/templates/Cuidado/listar_fichas.html
{% extends 'base.html' %}

{% block title %}Lista de Fichas Médicas{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Lista de Fichas Médicas</h2>

    <!-- Agregar mensajes de éxito o error -->
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <!-- Botón para agregar una nueva ficha (solo para veterinarios) -->
    {% if user.empleado.rol == 'Veterinario' %}
        <a href="{% url 'agregar_ficha' %}" class="btn btn-success mb-2">Agregar Ficha</a>
    {% endif %}

    <!-- Filtros de búsqueda -->
    <form method="GET" class="form-inline mb-2">
        <div class="form-group">
            <label for="search-mascota">Buscar por Mascota:</label>
            <input type="text" class="form-control mx-2" id="search-mascota" name="mascota" placeholder="Nombre de la Mascota">
        </div>
        <button type="submit" class="btn btn-primary">Buscar</button>
    </form>

    <table class="table table-responsive">
        <thead>
            <tr>
              {% if user.is_authenticated and not user.cliente %}
                <th>ID</th>
                {% endif %}
                <th>Cliente</th>
                <th>Mascota</th>
                <th>Veterinario</th>
                <th>Fecha</th>
                <th>Medicamento</th>
                <th>Dosis</th>
                <th>Instrucciones</th>
                <th>Exportar</th>
                {% if user.empleado.rol == 'Veterinario' %}
                <th>Acciones</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
          {% for ficha in fichas %}
          <tr>
            {% if user.is_authenticated and not user.cliente %}
              <td>{{ ficha.id }}</td>
              {% endif %}
              <td>{{ ficha.cliente.user.username }}</td>
              <td>{{ ficha.mascota.nombre }}</td>
              <td>{{ ficha.veterinario.user.first_name }} {{ ficha.veterinario.user.last_name }} {{ ficha.veterinario.second_last_name }}</td>
              <td>{{ ficha.fecha }}</td>
              <td>{{ ficha.medicamento }}</td>
              <td>{{ ficha.dosis }}</td>
              <td style="text-align: justify;">{{ ficha.instrucciones }}</td>
              <td>
                <a href="{% url 'generar_ficha_pdf' ficha.id %}" class="btn btn-primary btn-sm">Descargar</a>
            </td>
              {% if user.empleado.rol == 'Veterinario' %}
              <td>
                  <div class="d-flex align-items-center">
                          <a href="{% url 'editar_ficha' ficha.id %}" class="btn btn-primary btn-sm">Editar</a>
                          <a href="{% url 'confirmar_borrar_ficha' ficha.id %}" class="btn btn-danger btn-sm ml-2">Borrar</a>
                  </div>
              </td>
              {% endif %}
          </tr>
      {% endfor %}
        </tbody>
    </table>

    <nav aria-label="Paginación">
        <ul class="pagination">
          {% if fichas.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1">Primera</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ fichas.previous_page_number }}">Anterior</a>
            </li>
          {% endif %}
      
          {% for i in fichas.paginator.page_range %}
            <li class="page-item{% if i == fichas.number %} active{% endif %}">
              <a class="page-link" href="?page={{ i }}">{{ i }}{% if i == fichas.number %} <span class="sr-only">(current)</span>{% endif %}</a>
            </li>
          {% endfor %}
      
          {% if fichas.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ fichas.next_page_number }}">Siguiente</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ fichas.paginator.num_pages }}">Última</a>
            </li>
          {% endif %}
        </ul>
    </nav>
    <a href="#" id="volverAtrasBtn" class="btn btn-secondary mt-1">Volver atrás</a>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
      var volverAtrasBtn = document.getElementById("volverAtrasBtn");
  
      if (volverAtrasBtn) {
          volverAtrasBtn.addEventListener("click", function() {
              window.history.back();
          });
      }
  });
</script>

{% endblock %}